name: lint_rules
version: 0.0.1
description: Linr rules

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  dart_code_metrics: 5.5.1
  flutter_lints: 2.0.1

dev_dependencies:
  dependency_validator: 3.2.2